force-app/shared/objects/PermissionAssignmentRequest__c/PermissionAssignmentRequest__c.object-meta.xml
<CustomObject>
    <label>Permission Assignment Request</label>
    <nameField>
        <label>Email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permission Assignment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/PermissionAssignmentRequest__c/fields/CRM_PermissionSet__c.field-meta.xml
<CustomField>
    <fullName>CRM_PermissionSet__c</fullName>
    <label>Permission Set</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TAG_CreateReports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/permission-assignment/classes/PermissionAssignmentHandlerTest.cls
@IsTest
private class PermissionAssignmentHandlerTest {
    // PermissionAssignmentRequest__c request = getPermissionAssignmentRequests( 'TAG_CreateReports' );
	private static PermissionAssignmentRequest__c getPermissionAssignmentRequest( String permissionSetName ) {

		PermissionAssignmentRequest__c request = new PermissionAssignmentRequest__c(
			Name = UserInfo.getUserEmail(),
			CRM_PermissionSet__c = permissionSetName
			);

		return request;
	}
}