force-app/shared/objects/UnlockedPackage__c/UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/UnlockedPackage__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</description>
    <inlineHelpText
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/LatestReleasedSubscriberPackageVersionId__c.field-meta.xml
<CustomField>
    <fullName>LatestReleasedSubscriberPackageVersionId__c</fullName>
    <description>The latest package version (highest version number) that has been promoted to released</description>
    <inlineHelpText
    >The latest package version (highest version number) that has been promoted to released</inlineHelpText>
    <label>Latest Released Version Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/LatestReleasedVersionInstallOrder__c.field-meta.xml
<CustomField>
    <fullName>LatestReleasedVersionInstallOrder__c</fullName>
    <description
    >The logical installation order of the latest released version of this unlocked package. Populated by Apex and used to be able to query this object in order to know how to install all latest released versions of unlocked packages in the correct dependency order. Used by Github Action CI workflow to ensure the compatibility of released package versions.</description>
    <inlineHelpText
    >The logical installation order of the latest released version of this unlocked package. Used by Github Action CI workflow to ensure the compatibility of released package versions.</inlineHelpText>
    <label>Latest Released Version Install Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/SubscriberPackageId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberPackageId__c</fullName>
    <description
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</description>
    <inlineHelpText
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</inlineHelpText>
    <label>Subscriber Package Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package-dependency-viewer/classes/PackageUpdateService.cls
public with sharing class PackageUpdateService {

    public static void updateUnlockedPackageLatestReleasedFields() {
        List<PackageDependencyService.SimplePackageVersion> packageVersions = new PackageDependencyService().getDependenciesForLatestReleasedVersions();
        Map<Id, PackageDependencyService.SimplePackageVersion> packageVersionsByPackageId = getPackageVersionByPackageId(packageVersions);
        List<UnlockedPackage__c> packagesToUpdate = initializePackagesToUpdate(packageVersionsByPackageId);
        update packagesToUpdate;
    }

    private static List<UnlockedPackage__c> initializePackagesToUpdate(Map<Id, PackageDependencyService.SimplePackageVersion> packagesByPackageId) {
        Map<Id, Integer> installationOrderByPackageId = getInstallationOrderMap(packagesByPackageId.values());
        List<UnlockedPackage__c> upmUnlockedPackages = [SELECT Id, SubscriberPackageId__c FROM UnlockedPackage__c];
        for (UnlockedPackage__c upm : upmUnlockedPackages) {
            if (packagesByPackageId.containsKey(upm.SubscriberPackageId__c)) {
                upm.LatestReleasedVersionInstallOrder__c = installationOrderByPackageId.get(upm.SubscriberPackageId__c);
                upm.LatestReleasedSubscriberPackageVersionId__c = packagesByPackageId.get(upm.SubscriberPackageId__c).subscriberPackageVersionId;
                upm.LastQueried__c = Datetime.now();
            } else {
                upm.LatestReleasedVersionInstallOrder__c = null;
                upm.LatestReleasedSubscriberPackageVersionId__c = null;
            }
        }
        return upmUnlockedPackages;
    }

    private static Map<Id, Integer> getInstallationOrderMap(List<PackageDependencyService.SimplePackageVersion> packageVersions) {
        Map<Id, Integer> installationOrderByPackageId = new Map<Id, Integer>();
        Integer i = 0;
        for (PackageDependencyService.SimplePackageVersion spv : packageVersions) {
            installationOrderByPackageId.put(spv.subscriberPackageId, i);
            i++;
        }
        return installationOrderByPackageId;
    }

    private static Map<Id, PackageDependencyService.SimplePackageVersion> getPackageVersionByPackageId(List<PackageDependencyService.SimplePackageVersion> packageVersions) {
        Map<Id, PackageDependencyService.SimplePackageVersion> packageVersionsByPackageId = new Map<Id, PackageDependencyService.SimplePackageVersion>();
        for (PackageDependencyService.SimplePackageVersion spv : packageVersions) {
            packageVersionsByPackageId.put(spv.subscriberPackageId, spv);
        }
        return packageVersionsByPackageId;
    }
}