force-app/shared/objects/UnlockedPackage__c/UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/UnlockedPackage__c/fields/SubscriberPackageId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberPackageId__c</fullName>
    <description
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</description>
    <inlineHelpText
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</inlineHelpText>
    <label>Subscriber Package Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_Environment__c/UPM_Environment__c.object-meta.xml
<CustomObject>
    <description>Contains information about a given Salesforce Org</description>
    <label>Environment</label>
    <nameField>
        <label>
            Environment Labels</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UnlockedPackage__c.field-meta.xml
<CustomField>
    <fullName>UnlockedPackage__c</fullName>
    <description>The unlocked package the package version represents a version of</description>
    <label>Unlocked Package</label>
    <referenceTo>UPM_UnlockedPackage__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_Description__c.field-meta.xml
<CustomField>
    <fullName>UPM_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_Environment__c.field-meta.xml
<CustomField>
    <fullName>UPM_Environment__c</fullName>
    <label>Environment</label>
    <referenceTo>UPM_Environment__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>UPM_InstalledPackages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_IsBeta__c.field-meta.xml
<CustomField>
    <fullName>UPM_IsBeta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Beta</label>
    <type>Checkbox</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_IsHasKey__c.field-meta.xml
<CustomField>
    <fullName>UPM_IsHasKey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Key</label>
    <type>Checkbox</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_SubscriberPackageVersionId__c.field-meta.xml
<CustomField>
    <fullName>UPM_SubscriberPackageVersionId__c</fullName>
    <label>Subscriber Package Version Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_Version__c.field-meta.xml
<CustomField>
    <fullName>UPM_Version__c</fullName>
    <label>Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_UnlockedPackage__c/UPM_UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package-pipeline-viewer/classes/OrgCalloutService.cls
public with sharing class OrgCalloutService {

    private static String packageIdFilterString;
    private static Map<Id, Id> unlockedPackageIdBySubscriberPackageId = new Map<Id, Id>();

    static {
        String packageIdsString = '(';
        for (UPM_UnlockedPackage__c up : [SELECT Id, SubscriberPackageId__c FROM UPM_UnlockedPackage__c]) {
            packageIdsString += '\'' + up.SubscriberPackageId__c + '\',';
            unlockedPackageIdBySubscriberPackageId.put(up.SubscriberPackageId__c, up.Id);
        }
        packageIdsString = packageIdsString.removeEnd(',');
        packageIdsString += ')';
        packageIdFilterString = packageIdsString;
    }

    public static void refreshOrgInfo(Set<Id> orgIds) {
        List<UPM_Environment__c> orgs = [SELECT Id, Name, NamedCredential__c FROM UPM_Environment__c WHERE Id IN :orgIds ORDER BY SortOrder__c ASC];
        Map<String, UPM_Environment__c> namedCredentialOrgMap = new Map<String, UPM_Environment__c>();
        for (UPM_Environment__c org : orgs) {
            namedCredentialOrgMap.put(org.NamedCredential__c, org);
        }

        List<UPM_InstalledPackage__c> ipsToInsert = new List<UPM_InstalledPackage__c>();
        for (UPM_Environment__c org : orgs) {
            String body = doCallout(org.NamedCredential__c, packageIdFilterString);
            QueryResponseFormat qrf = QueryResponseFormat.parse(body);

            for (QueryResponseFormat.record record : qrf.records) {
                UPM_InstalledPackage__c ip = new UPM_InstalledPackage__c();
                ip.UPM_Environment__c = org.Id;
                ip.Name = record.subscriberPackage.name;
                ip.UPM_Description__c = record.subscriberPackageVersion.Description;
                ip.UPM_Version__c = record.subscriberPackageVersion.MajorVersion + '.' + record.subscriberPackageVersion.MinorVersion + '.' + record.subscriberPackageVersion.PatchVersion + '-' + record.subscriberPackageVersion.BuildNumber;
                ip.UPM_IsBeta__c = record.subscriberPackageVersion.IsBeta;
                ip.UPM_IsHasKey__c = record.subscriberPackageVersion.IsPasswordProtected;
                ip.UPM_SubscriberPackageVersionId__c = record.subscriberPackageVersion.Id;
                ip.UnlockedPackage__c = unlockedPackageIdBySubscriberPackageId.get(record.SubscriberPackageId);
                ipsToInsert.add(ip);
            }
        }

        delete [SELECT Id FROM UPM_InstalledPackage__c WHERE UPM_Environment__c IN :orgIds];
        insert ipsToInsert;
    }


    @AuraEnabled
    public static String doCallout(String namedCredential, String filterString) {
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint('callout:'
                + namedCredential
                + '/services/data/v48.0/tooling/query/?q=' +
                'SELECT+Id,' +
                '+SubscriberPackageId,' +
                '+SubscriberPackage.NamespacePrefix,' +
                '+SubscriberPackage.Name,' +
                '+SubscriberPackageVersion.Id,' +
                '+SubscriberPackageVersion.Name,' +
                '+SubscriberPackageVersion.Description,' +
                '+SubscriberPackageVersion.IsBeta,' +
                '+SubscriberPackageVersion.IsPasswordProtected,' +
                '+SubscriberPackageVersion.MajorVersion,' +
                '+SubscriberPackageVersion.MinorVersion,' +
                '+SubscriberPackageVersion.PatchVersion,' +
                '+SubscriberPackageVersion.BuildNumber,' +
                '+SubScriberPackageVersion.ReleaseState' +
                '+FROM+InstalledSubscriberPackage' +
                '+WHERE' +
                '+SubscriberPackageId+IN+' + filterString +
                '+ORDER+BY+SubscriberPackageId');
        req.setTimeout(120000);
        HttpResponse res = new Http().send(req);
        return res.getBody();
    }

}