force-app/shared/objects/UnlockedPackage__c/UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/UnlockedPackage__c/fields/ColorCode__c.field-meta.xml
<CustomField>
    <fullName>ColorCode__c</fullName>
    <description
    >Color code to set as the background color for tiles representing the package in the Development Pipeline tab. Use a 6-character HTML Hex Color Code, e.g &quot;FF0000&quot;</description>
    <inlineHelpText
    >Color code to set as the background color for tiles representing the package in the Development Pipeline tab. Use a 6-character HTML Hex Color Code, e.g &quot;FF0000&quot;</inlineHelpText>
    <label>Color Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/GitHubRepositoryPath__c.field-meta.xml
<CustomField>
    <fullName>GitHubRepositoryPath__c</fullName>
    <description
    >The path to the Unlocked Packages related Github Repository in the following format: https://github.com/:owner/:repo. For example &quot;https://github.com/mycompany/mypackagerepo&quot;.</description>
    <inlineHelpText
    >The path to the Unlocked Packages related Github Repository in the following format: https://github.com/:owner/:repo. For example &quot;https://github.com/mycompany/mypackagerepo&quot;.</inlineHelpText>
    <label>GitHub Repository Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</description>
    <inlineHelpText
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description
    >The team who owns the package. Used to filter packages in the Development Pipeline tab.</description>
    <inlineHelpText
    >The team who owns the package. Used to filter packages in the Development Pipeline tab.</inlineHelpText>
    <label>Team</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_Environment__c/UPM_Environment__c.object-meta.xml
<CustomObject>
    <description>Contains information about a given Salesforce Org</description>
    <label>Environment</label>
    <nameField>
        <label>
            Environment Labels</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package-pipeline-viewer/objects/UPM_Environment__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description>The date and time the environment was last sucessfully queried and updated with installed package information</description>
    <inlineHelpText>The date and time the environment was last sucessfully queried and updated with installed package information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UnlockedPackage__c.field-meta.xml
<CustomField>
    <fullName>UnlockedPackage__c</fullName>
    <description>The unlocked package the package version represents a version of</description>
    <label>Unlocked Package</label>
    <referenceTo>UPM_UnlockedPackage__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_Description__c.field-meta.xml
<CustomField>
    <fullName>UPM_Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_Environment__c.field-meta.xml
<CustomField>
    <fullName>UPM_Environment__c</fullName>
    <label>Environment</label>
    <referenceTo>UPM_Environment__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>UPM_InstalledPackages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_IsBeta__c.field-meta.xml
<CustomField>
    <fullName>UPM_IsBeta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Beta</label>
    <type>Checkbox</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_IsHasKey__c.field-meta.xml
<CustomField>
    <fullName>UPM_IsHasKey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Key</label>
    <type>Checkbox</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_InstalledPackage__c/fields/UPM_Version__c.field-meta.xml
<CustomField>
    <fullName>UPM_Version__c</fullName>
    <label>Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/package-pipeline-viewer/objects/UPM_UnlockedPackage__c/UPM_UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/package-pipeline-viewer/classes/DevopsDashboardController.cls
public with sharing class DevopsDashboardController {

    @AuraEnabled
    public static List<UPM_Environment__c> getEnvironmentData() {
        return [
                SELECT Id,
                        Name,
                        NamedCredential__c,
                        SortOrder__c,
                        LastQueried__c, (
                        SELECT Id,
                                Name,
                                UPM_Version__c,
                                UPM_Description__c,
                                UPM_IsHasKey__c,
                                UPM_IsBeta__c,
                                UnlockedPackage__c,
                                UnlockedPackage__r.GitHubRepositoryPath__c,
                                UnlockedPackage__r.ColorCode__c,
                                UnlockedPackage__r.Team__c
                        FROM UPM_InstalledPackages__r
                        ORDER BY UnlockedPackage__r.Team__c ASC
                )
                FROM UPM_Environment__c
                ORDER BY SortOrder__c ASC
        ];
    }

    @AuraEnabled
    public static void refreshInstalledPackageData(List<Id> orgIds) {
        new InstalledPackageService(new Set<Id>(orgIds)).refreshInstalledPackages();
    }
}