force-app/shared/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <description>Contains information about a given Salesforce Org</description>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/Environment__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description
    >The date and time the environment was last sucessfully queried and updated with installed package information</description>
    <inlineHelpText
    >The date and time the environment was last sucessfully queried and updated with installed package information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/shared/objects/Environment__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description
    >API Name for the Named Credential related to the org</description>
    <inlineHelpText
    >API Name for the Named Credential related to the org</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/objects/Environment__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description
    >The org&#39;s placement in the pipeline. Ascending from left-to-right.</description>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/shared/objects/InstalledPackage__c/InstalledPackage__c.object-meta.xml
<CustomObject>
    <label>Installed Package</label>
    <nameField>
        <label>Installed Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/shared/objects/InstalledPackage__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/IsBeta__c.field-meta.xml
<CustomField>
    <fullName>IsBeta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Beta</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/IsHasKey__c.field-meta.xml
<CustomField>
    <fullName>IsHasKey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Key</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/UnlockedPackage__c.field-meta.xml
<CustomField>
    <fullName>UnlockedPackage__c</fullName>
    <description
    >The unlocked package the package version represents a version of</description>
    <label>Unlocked Package</label>
    <referenceTo>UnlockedPackage__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/UnlockedPackage__c/fields/ColorCode__c.field-meta.xml
<CustomField>
    <fullName>ColorCode__c</fullName>
    <description
    >Color code to set as the background color for tiles representing the package in the Development Pipeline tab. Use a 6-character HTML Hex Color Code, e.g &quot;FF0000&quot;</description>
    <inlineHelpText
    >Color code to set as the background color for tiles representing the package in the Development Pipeline tab. Use a 6-character HTML Hex Color Code, e.g &quot;FF0000&quot;</inlineHelpText>
    <label>Color Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/GitHubRepositoryPath__c.field-meta.xml
<CustomField>
    <fullName>GitHubRepositoryPath__c</fullName>
    <description
    >The path to the Unlocked Packages related Github Repository in the following format: https://github.com/:owner/:repo. For example &quot;https://github.com/mycompany/mypackagerepo&quot;.</description>
    <inlineHelpText
    >The path to the Unlocked Packages related Github Repository in the following format: https://github.com/:owner/:repo. For example &quot;https://github.com/mycompany/mypackagerepo&quot;.</inlineHelpText>
    <label>GitHub Repository Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</description>
    <inlineHelpText
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/LatestReleasedVersionInstallOrder__c.field-meta.xml
<CustomField>
    <fullName>LatestReleasedVersionInstallOrder__c</fullName>
    <description
    >The logical installation order of the latest released version of this unlocked package. Populated by Apex and used to be able to query this object in order to know how to install all latest released versions of unlocked packages in the correct dependency order. Used by Github Action CI workflow to ensure the compatibility of released package versions.</description>
    <inlineHelpText
    >The logical installation order of the latest released version of this unlocked package. Used by Github Action CI workflow to ensure the compatibility of released package versions.</inlineHelpText>
    <label>Latest Released Version Install Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description
    >The team who owns the package. Used to filter packages in the Development Pipeline tab.</description>
    <inlineHelpText
    >The team who owns the package. Used to filter packages in the Development Pipeline tab.</inlineHelpText>
    <label>Team</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/development-pipeline/classes/DevelopmentPipelineController.cls
public with sharing class DevelopmentPipelineController {

    @AuraEnabled
    public static List<Environment__c> getEnvironmentData() {
        return [
                SELECT Id,
                        Name,
                        NamedCredential__c,
                        SortOrder__c,
                        LastQueried__c, (
                        SELECT Id,
                                Name,
                                Version__c,
                                Description__c,
                                IsHasKey__c,
                                IsBeta__c,
                                UnlockedPackage__c,
                                UnlockedPackage__r.GitHubRepositoryPath__c,
                                UnlockedPackage__r.ColorCode__c,
                                UnlockedPackage__r.Team__c
                        FROM InstalledPackages__r
                        ORDER BY UnlockedPackage__r.Team__c ASC,
                                UnlockedPackage__r.LatestReleasedVersionInstallOrder__c ASC
                )
                FROM Environment__c
                ORDER BY SortOrder__c ASC
        ];
    }

    @AuraEnabled
    public static void refreshInstalledPackageData(List<Id> orgIds) {
        new InstalledPackageService(new Set<Id>(orgIds)).refreshInstalledPackages();
    }
}