force-app/shared/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <description>Contains information about a given Salesforce Org</description>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/Environment__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description
    >API Name for the Named Credential related to the org</description>
    <inlineHelpText
    >API Name for the Named Credential related to the org</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/objects/Environment__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description
    >The org&#39;s placement in the pipeline. Ascending from left-to-right.</description>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/shared/objects/InstalledPackage__c/InstalledPackage__c.object-meta.xml
<CustomObject>
    <label>Installed Package</label>
    <nameField>
        <label>Installed Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/shared/objects/InstalledPackage__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/UnlockedPackage__c.field-meta.xml
<CustomField>
    <fullName>UnlockedPackage__c</fullName>
    <description
    >The unlocked package the package version represents a version of</description>
    <label>Unlocked Package</label>
    <referenceTo>UnlockedPackage__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/UnlockedPackage__c/fields/SubscriberPackageId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberPackageId__c</fullName>
    <description
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</description>
    <inlineHelpText
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</inlineHelpText>
    <label>Subscriber Package Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/development-pipeline/classes/DevelopmentPipelineControllerTest.cls
@isTest
public class DevelopmentPipelineControllerTest {

    @TestSetup
    private static void makeData(){
       
        List<UnlockedPackage__c> packages = new List<UnlockedPackage__c>();
        packages.add(new UnlockedPackage__c(Name = 'test-package-1', SubscriberPackageId__c = '0332o000000TyICAA0'));
        packages.add(new UnlockedPackage__c(Name = 'test-package-2', SubscriberPackageId__c = '0332o000000TyIHAA0'));
        packages.add(
            new UnlockedPackage__c(Name = 'test-package-3', SubscriberPackageId__c = '0332o000000XXXXXXX') // Doesn't exist in mock response
        );
        insert packages;

        List<Environment__c> environments = new List<Environment__c>();
        environments.add(
            new Environment__c(Name = 'Integration Sandbox', NamedCredential__c = 'INT', SortOrder__c = 0)
        );
        environments.add(new Environment__c(Name = 'UAT Sandbox', NamedCredential__c = 'UAT', SortOrder__c = 1));
        insert environments;


        List<InstalledPackage__c> installedPackages= new List<InstalledPackage__c>();
        installedPackages.add(new InstalledPackage__c(Name='Test Installed Package', UnlockedPackage__c=packages[0].Id, Environment__c=environments[0].Id));
        insert installedPackages;
    }

    @isTest
    public static void testGetEnvironmentData() {

        Test.startTest();
        List<Environment__c> result = DevelopmentPipelineController.getEnvironmentData();
        Test.stopTest();
        
        // Assert the result
        System.assertEquals(2, result.size());
        Environment__c retrievedEnvironment = result[0];
        System.assertEquals('Integration Sandbox', retrievedEnvironment.Name);
        System.assertEquals(0, retrievedEnvironment.SortOrder__c);
        
        List<InstalledPackage__c> installedPackages = [SELECT Name FROM InstalledPackage__c];
        System.assertEquals(1, installedPackages.size());
        InstalledPackage__c retrievedPackage = installedPackages[0];
        System.assertEquals('Test Installed Package', retrievedPackage.Name);
    }
    
    @isTest
    public static void testRefreshInstalledPackageData() {
        MultiRequestMockSameEndpoint responses = new MultiRequestMockSameEndpoint(
            new List<String>{ TestDataFactory_PlatformAdmin.int_environment_query_response, TestDataFactory_PlatformAdmin.uat_environment_query_response }
        );
        Test.setMock(HttpCalloutMock.class, responses);

        Test.startTest();
        Environment__c env=[SELECT Id FROM Environment__c LIMIT 1];
        List<Id> orgIds = new List<Id>{env.Id};
        DevelopmentPipelineController.refreshInstalledPackageData(orgIds);
        Test.stopTest();

        List<InstalledPackage__c> intInstalledPackages = [
            SELECT Id
            FROM InstalledPackage__c
            WHERE Environment__r.Name = 'Integration Sandbox'
        ];
        System.assertEquals(2, intInstalledPackages.size());
    }
}