force-app/shared/objects/Environment__c/Environment__c.object-meta.xml
<CustomObject>
    <description>Contains information about a given Salesforce Org</description>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/Environment__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description
    >The date and time the environment was last sucessfully queried and updated with installed package information</description>
    <inlineHelpText
    >The date and time the environment was last sucessfully queried and updated with installed package information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/shared/objects/Environment__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <description
    >API Name for the Named Credential related to the org</description>
    <inlineHelpText
    >API Name for the Named Credential related to the org</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/objects/Environment__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description
    >The org&#39;s placement in the pipeline. Ascending from left-to-right.</description>
    <label>Sort Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/shared/objects/InstalledPackage__c/InstalledPackage__c.object-meta.xml
<CustomObject>
    <label>Installed Package</label>
    <nameField>
        <label>Installed Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installed Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/shared/objects/InstalledPackage__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <referenceTo>Environment__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/IsBeta__c.field-meta.xml
<CustomField>
    <fullName>IsBeta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Beta</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/IsHasKey__c.field-meta.xml
<CustomField>
    <fullName>IsHasKey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Key</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/SubscriberPackageVersionId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberPackageVersionId__c</fullName>
    <label>Subscriber Package Version Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/shared/objects/InstalledPackage__c/fields/UnlockedPackage__c.field-meta.xml
<CustomField>
    <fullName>UnlockedPackage__c</fullName>
    <description
    >The unlocked package the package version represents a version of</description>
    <label>Unlocked Package</label>
    <referenceTo>UnlockedPackage__c</referenceTo>
    <relationshipLabel>Installed Packages</relationshipLabel>
    <relationshipName>InstalledPackages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/UnlockedPackage__c.object-meta.xml
<CustomObject>
    <description>Represents an Unlocked Package that should be represented in the pipeline overview</description>
    <label>Unlocked Package</label>
    <nameField>
        <label>Unlocked Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unlocked Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/objects/UnlockedPackage__c/fields/LastQueried__c.field-meta.xml
<CustomField>
    <fullName>LastQueried__c</fullName>
    <description
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</description>
    <inlineHelpText
    >The date and time the package was last successfully queried and updated with latest released version and dependency information</inlineHelpText>
    <label>Last Queried</label>
    <type>DateTime</type>
</CustomField>

force-app/shared/objects/UnlockedPackage__c/fields/SubscriberPackageId__c.field-meta.xml
<CustomField>
    <fullName>SubscriberPackageId__c</fullName>
    <description
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</description>
    <inlineHelpText
    >The Unlocked Packages 18 character SubscriberPackageId (starts with 033). Can be viewed through the sfdx force:package:list command with the --verbose parameter.</inlineHelpText>
    <label>Subscriber Package Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/development-pipeline/classes/InstalledPackageService.cls
public class InstalledPackageService {
    private Set<Id> orgIds;
    private ToolingAPI tooling;
    private Map<String, Id> unlockedPackageIdBySubscriberPackageId;
    private Map<String, Environment__c> environmentByNamedCredential;
    private Map<String, List<ToolingAPI.InstalledSubscriberPackage>> installedPackagesByNamedCredential;

    public InstalledPackageService(Set<Id> orgIds) {
        this.orgIds = orgIds;
        getUnlockedPackageIdBySubscriberPackageId();
    }

    public void refreshInstalledPackages() {
        getEnvironmentsByNamedCredential();
        queryInstalledPackagesByOrg();
        deleteExistingInstalledPackageRecords();
        insertNewInstalledPackageRecords();
        updateEnvironmentLastQueriedTimestamps();
    }

    private void insertNewInstalledPackageRecords() {
        List<InstalledPackage__c> installedPackagesToInsert = new List<InstalledPackage__c>();
        for (
            String namedCredential : this.installedPackagesByNamedCredential.keySet()
        ) {
            for (
                ToolingAPI.InstalledSubscriberPackage isp : this.installedPackagesByNamedCredential.get(
                    namedCredential
                )
            ) {
                installedPackagesToInsert.add(
                    createInstalledPackageRecord(isp, namedCredential)
                );
            }
        }
        insert installedPackagesToInsert;
    }

    private InstalledPackage__c createInstalledPackageRecord(
        ToolingAPI.InstalledSubscriberPackage isp,
        String namedCredential
    ) {
        InstalledPackage__c ip = new InstalledPackage__c();
        ip.Environment__c = environmentByNamedCredential.get(namedCredential)
            .Id;
        System.debug(isp.subscriberPackageId);
        ip.UnlockedPackage__c = unlockedPackageIdBySubscriberPackageId.get(
            isp.subscriberPackageId
        );
        ip.Description__c = isp.subscriberPackageVersion.description;
        ip.Name = isp.subscriberPackage.name;
        ip.Version__c =
            isp.subscriberPackageVersion.MajorVersion +
            '.' +
            isp.subscriberPackageVersion.MinorVersion +
            '.' +
            isp.subscriberPackageVersion.PatchVersion +
            '-' +
            isp.subscriberPackageVersion.BuildNumber;
        ip.IsBeta__c = isp.subscriberPackageVersion.IsBeta;
        ip.IsHasKey__c = isp.subscriberPackageVersion.IsPasswordProtected;
        ip.SubscriberPackageVersionId__c = isp.subscriberPackageVersion.Id;
        return ip;
    }

    private void getEnvironmentsByNamedCredential() {
        Map<String, Environment__c> environmentByNamedCredential = new Map<String, Environment__c>();
        for (Environment__c org : [
            SELECT Id, Name, NamedCredential__c
            FROM Environment__c
            WHERE Id IN :this.orgIds
            ORDER BY SortOrder__c ASC
        ]) {
            environmentByNamedCredential.put(org.NamedCredential__c, org);
        }
        this.environmentByNamedCredential = environmentByNamedCredential;
    }

    private void queryInstalledPackagesByOrg() {
        Map<String, List<ToolingAPI.InstalledSubscriberPackage>> installedPackagesByNamedCredential = new Map<String, List<ToolingAPI.InstalledSubscriberPackage>>();
        for (
            String namedCredential : this.environmentByNamedCredential.keySet()
        ) {
            this.tooling = new ToolingAPI(namedCredential);
            installedPackagesByNamedCredential.put(
                namedCredential,
                getInstalledPackageVersionsForEnvironment()
            );
        }
        this.installedPackagesByNamedCredential = installedPackagesByNamedCredential;
    }

    private List<ToolingAPI.InstalledSubscriberPackage> getInstalledPackageVersionsForEnvironment() {
        ToolingAPI.QueryResult result = tooling.query(
            'SELECT Id, ' +
            'SubscriberPackageId,' +
            'SubscriberPackage.Name,' +
            'SubscriberPackageVersion.Id,' +
            'SubscriberPackageVersion.Description,' +
            'SubscriberPackageVersion.IsBeta,' +
            'SubscriberPackageVersion.IsPasswordProtected,' +
            'SubscriberPackageVersion.MajorVersion,' +
            'SubscriberPackageVersion.MinorVersion,' +
            'SubscriberPackageVersion.PatchVersion,' +
            'SubscriberPackageVersion.BuildNumber' +
            ' FROM InstalledSubscriberPackage' +
            ' WHERE' +
            ' SubscriberPackageId IN' +
            UnlockedPackageService.getUnlockedPackageSOQLFilterFromRecords() +
            ' ORDER BY SubscriberPackageId DESC'
        );
        return (List<ToolingAPI.InstalledSubscriberPackage>) result.records;
    }

    private void deleteExistingInstalledPackageRecords() {
        delete [
            SELECT Id
            FROM InstalledPackage__c
            WHERE Environment__c IN :this.orgIds
        ];
    }

    private void getUnlockedPackageIdBySubscriberPackageId() {
        this.unlockedPackageIdBySubscriberPackageId = new Map<String, Id>();
        for (UnlockedPackage__c up : [
            SELECT Id, SubscriberPackageId__c
            FROM UnlockedPackage__c
        ]) {
            this.unlockedPackageIdBySubscriberPackageId.put(
                up.SubscriberPackageId__c,
                up.Id
            );
        }
    }

    private void updateEnvironmentLastQueriedTimestamps() {
        // Instantiate new Environment records in order to update LastQueried field
        List<Environment__c> environmentsToUpdate = new List<Environment__c>();
        for (Id envId : orgIds) {
            environmentsToUpdate.add(
                new Environment__c(Id = envId, LastQueried__c = Datetime.now())
            );
        }
        update environmentsToUpdate;
    }
}